name: logger_sdk
description: Cross-platform logging SDK implemented in Dart.
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.11.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
